### PR TITLE
RouteGroup CRD should be optional

### LINKED ISSUE #312: v0.10.0+ will fail to run if RouteGroups CRD is not installed
Recently tried a newer version of this, and found I had to revert because we do not have this CRD installed.

Should this be optional for those continuing to use traditional Ingress records?

### PR DESCRIPTION
**Pull request by szuecs**
fix #312 - make RouteGroup CRD optional and log a warning to notify the user about RouteGroups

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

File: kubernetes/adapter.go [hunk 1]
```diff
@@ -300,10 +301,16 @@ func (a *Adapter) IngressFiltersString() string {
 func (a *Adapter) ListResources() ([]*Ingress, error) {
 	ings, err := a.ListIngress()
 	if err != nil {
+		log.Errorf("Failed to list ingress: %v", err)
```
Comment (mikkeloscar) [inline kubernetes/adapter.go]: I would not log an error here since we return it on the line below and handle it from the caller.

File: kubernetes/client.go [hunk 2]
```diff
@@ -84,16 +87,20 @@ func (c *simpleClient) get(resource string) (io.ReadCloser, error) {
...
-		resp.Body.Close()
-		return nil, err
+
+	if resp.StatusCode == http.StatusOK {
+		return resp.Body, nil
 	}
-	return resp.Body, nil
+	defer resp.Body.Close()
+
+	if resp.StatusCode == int(http.StatusNotFound) {
```
Comment (mikkeloscar) [inline kubernetes/client.go]: nit: it's already an `int`

File: kubernetes/adapter.go (hunk 1 above)
Comment (szuecs) [reply kubernetes/adapter.go]: Ỳep duplication of logs, dropped

File: kubernetes/client.go (hunk 2 above)
Comment (szuecs) [reply kubernetes/client.go]: yeah left over of some weird debugging

File: kubernetes/adapter.go [hunk 3]
```diff
@@ -304,6 +305,11 @@ func (a *Adapter) ListResources() ([]*Ingress, error) {
 	}
 	rgs, err := a.ListRoutegroups()
 	if err != nil {
+		log.Warnf("Failed to list RouteGroups: %v, to get more information https://opensource.zalando.com/skipper/kubernetes/routegroups/#routegroups", err)
```
Comment (mikkeloscar) [inline kubernetes/adapter.go]: I'm afraid this will be quite spammy in the logs as it will happen every sync interval. IMO it should be ok to run without RouteGroup support and you don't want to see a lot of logs telling the same thing if you can't turn it off.

Either we can add a flag to disable route groups completely, or we can detect the first time we try to list routegroups and e.g. set a field `a.routeGroupSupport = false` and only log `if a.routeGroupSupport`. WDYT?

Comment (szuecs) [reply kubernetes/adapter.go]: From 9 to 10 lines per interval is too spammy?

Comment (szuecs) [reply kubernetes/adapter.go]: The problem with storing the value is that after CRD apply it does not work, but you would have to delete the pod to retry.

Comment (mikkeloscar) [reply kubernetes/adapter.go]: You could still try to list the routes every interval (and reset the flag). I just think it doesn't bring any value to the user to log a warning that they can't do anything about (apart from deploying the CRD which they may not need/want).

Comment (szuecs) [reply kubernetes/adapter.go]: This makes sense!
I added as suggested the check

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:
